version: '3'

services:
  web:
    build:
      context: bugo-site
    volumes:
      # - node-modules:/workspace/node_modules
      - ./bugo-site/src:/workspace/src

  api:
    build:
      context: bugo-api

  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  reverse:
    image: nginx
    ports:
      - 8080:8080
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - <path/to/your/certs>:/etc/ssl/private



volumes:
  postgres-data:
  node-modules: